import React from 'react';
import {
  Sparkles,
  Database,
  ShieldCheck,
  BrainCircuit,
  Zap,
  ArrowRight,
  BarChart3,
  DollarSign,
  Activity,
  Layers,
  Lock,
  UserCheck
} from 'lucide-react';
import { GoogleLogin } from '@react-oauth/google';

export function LandingPage({ onTryFree, onGoogleSuccess, onGoogleError, user, googleClientId }) {
  const features = [
    {
      icon: BrainCircuit,
      title: "Self-Healing SQL",
      description:
        "Generate, validate and automatically repair SQL when a query encounters schema or syntax issues."
    },
    {
      icon: BarChart3,
      title: "Automatic Visualizations",
      description:
        "Turn database results into clean tables, charts and KPI views without building dashboards manually."
    },
    {
      icon: Database,
      title: "Bring Your Own Data",
      description:
        "Upload CSV, Excel or JSON files and make your datasets queryable in seconds."
    },
    {
      icon: Activity,
      title: "Usage & Observability",
      description:
        "Monitor tokens, latency, estimated costs, retries and query history with integrated telemetry."
    }
  ];

  const sampleQueries = [
    "What is the total revenue generated by each product category?",
    "Show the top 3 customers who spent the most money and their countries.",
    "Give me the count and total order value for each order status.",
    "Which products have low stock (< 35 items) and their prices?"
  ];

  return (
    <div className="space-y-16 py-4 pb-12">
      {/* Hero Section */}
      <div className="relative overflow-hidden rounded-3xl glass-panel border border-slate-800 p-8 sm:p-12 lg:p-16 text-center space-y-8 bg-gradient-to-b from-slate-900/90 via-slate-900/50 to-slate-950/90 shadow-2xl">
        {/* Glow Accents */}
        <div className="absolute -top-24 left-1/2 -translate-x-1/2 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-1/2 -right-24 w-72 h-72 bg-purple-500/10 rounded-full blur-3xl pointer-events-none" />

        {/* Top Tagline Badge */}
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/30 text-indigo-300 text-xs font-semibold tracking-wide">
          <Sparkles className="w-3.5 h-3.5 text-cyan-400" />
          <span>Enterprise AI Data Platform &amp; Telemetry Studio</span>
        </div>

        {/* Hero Title */}
        <h1 className="text-3xl sm:text-5xl lg:text-6xl font-black text-white tracking-tight leading-tight max-w-4xl mx-auto">
          Text2SQL with{' '}
          <span className="bg-gradient-to-r from-cyan-400 via-indigo-400 to-purple-400 bg-clip-text text-transparent">
            User Cost Tracking
          </span>
        </h1>

        {/* Hero Description */}
        <p className="text-slate-300 text-base sm:text-lg max-w-2xl mx-auto leading-relaxed">
          Ask natural-language questions to SQLite databases, generate self-healing SQL queries, auto-render business intelligence charts, and track individual LLM token costs through Langfuse.
        </p>

        {/* CTA Buttons Container */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
          {/* Try for Free (Guest Mode) */}
          <button
            onClick={onTryFree}
            className="w-full sm:w-auto px-8 py-3.5 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-bold text-sm shadow-xl shadow-cyan-500/25 transition transform hover:-translate-y-0.5 flex items-center justify-center gap-2.5"
          >
            <Zap className="w-4 h-4 text-cyan-200" />
            <span>Try for Free (No Login Needed)</span>
            <ArrowRight className="w-4 h-4" />
          </button>

          {/* Google Sign-In */}
          {!user ? (
            <div className="w-full sm:w-auto flex justify-center">
              {googleClientId ? (
                <GoogleLogin
                  onSuccess={onGoogleSuccess}
                  onError={onGoogleError}
                  theme="filled_blue"
                  shape="circle"
                  size="large"
                  text="signin_with"
                />
              ) : (
                <button
                  onClick={() => alert("Google Client ID not set in .env. Please configure GOOGLE_CLIENT_ID.")}
                  className="px-6 py-3 rounded-xl bg-slate-800 border border-slate-700 text-slate-300 text-xs font-semibold hover:bg-slate-700 transition flex items-center gap-2"
                >
                  <Lock className="w-4 h-4 text-purple-400" />
                  <span>Google Sign In (Requires GOOGLE_CLIENT_ID)</span>
                </button>
              )}
            </div>
          ) : (
            <div className="flex items-center gap-3 bg-slate-800/80 px-5 py-3 rounded-xl border border-slate-700">
              <UserCheck className="w-4 h-4 text-emerald-400" />
              <span className="text-xs text-slate-200 font-medium">Logged in as {user.name}</span>
            </div>
          )}
        </div>

        {/* Feature Pill Tags */}
        <div className="flex flex-wrap items-center justify-center gap-6 pt-6 text-xs text-slate-400">
          <div className="flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>Google OAuth 2.0 Security</span>
          </div>
          <div className="flex items-center gap-1.5">
            <Activity className="w-4 h-4 text-purple-400" />
            <span>Langfuse Cost &amp; Token Telemetry</span>
          </div>
          <div className="flex items-center gap-1.5">
            <Layers className="w-4 h-4 text-cyan-400" />
            <span>SQLite &amp; Custom CSV Imports</span>
          </div>
        </div>
      </div>

      {/* Feature Cards Grid */}
      <div className="space-y-6">
        <div className="text-center space-y-2">
          <h2 className="text-2xl font-bold text-white">Platform Capabilities</h2>
          <p className="text-xs text-slate-400">Built for seamless data exploration and transparent LLM cost monitoring.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {features.map((f, i) => {
            const Icon = f.icon;
            return (
              <div
                key={i}
                className="glass-card p-6 rounded-2xl border border-slate-800/80 hover:border-slate-700 transition shadow-xl space-y-3"
              >
                <div className={`w-10 h-10 rounded-xl bg-gradient-to-tr ${f.color} p-2 text-slate-950 flex items-center justify-center shadow-lg`}>
                  <Icon className="w-5 h-5" />
                </div>
                <h3 className="text-base font-bold text-slate-100">{f.title}</h3>
                <p className="text-xs text-slate-400 leading-relaxed">{f.description}</p>
              </div>
            );
          })}
        </div>
      </div>

      {/* Sample Query Prompts Showcase */}
      <div className="glass-panel p-8 rounded-2xl border border-slate-800 space-y-4">
        <h3 className="text-base font-bold text-white flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-cyan-400" />
          Example Natural-Language Questions You Can Ask
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {sampleQueries.map((q, idx) => (
            <div
              key={idx}
              className="p-3.5 rounded-xl bg-slate-900/70 border border-slate-800 text-xs text-slate-300 flex items-center justify-between hover:border-cyan-500/40 transition cursor-pointer"
              onClick={onTryFree}
            >
              <span>"{q}"</span>
              <ArrowRight className="w-3.5 h-3.5 text-cyan-400 shrink-0 ml-2" />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// import React from 'react';
// import {
//   Sparkles,
//   Database,
//   ShieldCheck,
//   BrainCircuit,
//   Zap,
//   ArrowRight,
//   BarChart3,
//   DollarSign,
//   Activity,
//   Layers,
//   Lock,
//   UserCheck,
//   LogOut,
//   Check,
//   ChevronRight
// } from 'lucide-react';
// import { GoogleLogin } from '@react-oauth/google';

// export function LandingPage({
//   onTryFree,
//   onGoogleSuccess,
//   onGoogleError,
//   onSignOut,
//   user,
//   googleClientId
// }) {
//   const features = [
//     {
//       icon: BrainCircuit,
//       title: "Self-Healing SQL",
//       description:
//         "Generate, validate and automatically repair SQL when a query encounters schema or syntax issues."
//     },
//     {
//       icon: BarChart3,
//       title: "Automatic Visualizations",
//       description:
//         "Turn database results into clean tables, charts and KPI views without building dashboards manually."
//     },
//     {
//       icon: Database,
//       title: "Bring Your Own Data",
//       description:
//         "Upload CSV, Excel or JSON files and make your datasets queryable in seconds."
//     },
//     {
//       icon: Activity,
//       title: "Usage & Observability",
//       description:
//         "Monitor tokens, latency, estimated costs, retries and query history with integrated telemetry."
//     }
//   ];

//   const sampleQueries = [
//     "What is the total revenue generated by each product category?",
//     "Show the top 3 customers who spent the most money.",
//     "Give me the count and total order value for each order status.",
//     "Which products have low stock and what are their prices?"
//   ];

//   return (
//     <div className="min-h-screen overflow-hidden bg-[#08090b] text-white">

//       {/* ========================================================= */}
//       {/* NAVBAR */}
//       {/* ========================================================= */}

//       <header className="sticky top-0 z-50 border-b border-white/[0.07] bg-[#08090b]/90 backdrop-blur-xl">
//         <div className="mx-auto flex h-[68px] max-w-7xl items-center justify-between px-5 sm:px-8">

//           {/* Brand */}
//           <button
//             onClick={onTryFree}
//             className="group flex items-center gap-3"
//           >
//             <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-[#08090b] shadow-sm">
//               <Database className="h-[17px] w-[17px]" />
//             </div>

//             <div className="text-left">
//               <div className="text-[15px] font-semibold tracking-[-0.02em] text-white">
//                 TextQuery
//               </div>
//               <div className="hidden text-[9px] font-medium uppercase tracking-[0.16em] text-[#666b73] sm:block">
//                 Data Intelligence
//               </div>
//             </div>
//           </button>


//           {/* Navbar Actions */}
//           <div className="flex items-center gap-2">

//             <button
//               onClick={onTryFree}
//               className="hidden rounded-lg px-4 py-2.5 text-xs font-medium text-[#a7abb2] transition hover:bg-white/[0.05] hover:text-white sm:block"
//             >
//               Try for free
//             </button>

//             {!user ? (

//               googleClientId ? (

//                 <div className="overflow-hidden rounded-lg">
//                   <GoogleLogin
//                     onSuccess={onGoogleSuccess}
//                     onError={onGoogleError}
//                     theme="filled_black"
//                     shape="rectangular"
//                     size="medium"
//                     text="signin_with"
//                   />
//                 </div>

//               ) : (

//                 <button
//                   onClick={() =>
//                     alert(
//                       "Google Client ID not set in .env. Please configure GOOGLE_CLIENT_ID."
//                     )
//                   }
//                   className="flex items-center gap-2 rounded-lg border border-white/[0.1] bg-white/[0.04] px-4 py-2.5 text-xs font-medium text-[#d7d9dc] transition hover:border-white/[0.18] hover:bg-white/[0.07]"
//                 >
//                   <Lock className="h-3.5 w-3.5 text-[#8b93a1]" />
//                   Sign in with Google
//                 </button>

//               )

//             ) : (

//               <div className="flex items-center gap-2">

//                 {/* User */}
//                 <div className="hidden items-center gap-2.5 rounded-lg border border-white/[0.08] bg-white/[0.035] px-3 py-2 sm:flex">

//                   <div className="flex h-6 w-6 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-violet-500 text-[9px] font-bold text-white">
//                     {user.name?.charAt(0)?.toUpperCase() || "U"}
//                   </div>

//                   <span className="max-w-[120px] truncate text-xs font-medium text-[#d7d9dc]">
//                     {user.name}
//                   </span>

//                 </div>

//                 {/* Sign out */}
//                 <button
//                   onClick={onSignOut}
//                   className="group flex items-center gap-2 rounded-lg border border-white/[0.08] bg-white/[0.035] px-3 py-2.5 text-xs font-medium text-[#a7abb2] transition hover:border-red-400/20 hover:bg-red-400/[0.06] hover:text-red-300"
//                 >
//                   <LogOut className="h-3.5 w-3.5 transition-transform group-hover:-translate-x-0.5" />
//                   <span className="hidden sm:inline">
//                     Sign out
//                   </span>
//                 </button>

//               </div>

//             )}

//           </div>
//         </div>
//       </header>


//       {/* ========================================================= */}
//       {/* HERO */}
//       {/* ========================================================= */}

//       <main>

//         <section className="relative border-b border-white/[0.06]">

//           {/* Background lighting */}
//           <div className="pointer-events-none absolute inset-0 overflow-hidden">

//             <div className="absolute left-1/2 top-[-220px] h-[600px] w-[900px] -translate-x-1/2 rounded-full bg-blue-600/[0.08] blur-[130px]" />

//             <div className="absolute left-[15%] top-[350px] h-[300px] w-[300px] rounded-full bg-cyan-500/[0.035] blur-[100px]" />

//             <div className="absolute right-[5%] top-[500px] h-[350px] w-[350px] rounded-full bg-violet-500/[0.035] blur-[120px]" />

//             <div
//               className="absolute inset-0 opacity-[0.025]"
//               style={{
//                 backgroundImage:
//                   'linear-gradient(rgba(255,255,255,0.7) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.7) 1px, transparent 1px)',
//                 backgroundSize: '64px 64px'
//               }}
//             />

//           </div>


//           <div className="relative mx-auto max-w-7xl px-5 pb-20 pt-20 sm:px-8 sm:pb-28 sm:pt-28 lg:pt-32">

//             <div className="grid items-center gap-16 lg:grid-cols-[0.95fr_1.05fr]">

//               {/* ================================================= */}
//               {/* HERO COPY */}
//               {/* ================================================= */}

//               <div>

//                 <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/[0.09] bg-white/[0.035] px-3.5 py-2 text-[10px] font-medium tracking-wide text-[#9da2aa]">

//                   <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.7)]" />

//                   AI-powered data analytics

//                   <ChevronRight className="h-3 w-3 text-[#5f646c]" />

//                 </div>


//                 <h1 className="max-w-2xl text-[46px] font-semibold leading-[1.04] tracking-[-0.045em] text-white sm:text-6xl lg:text-[70px]">

//                   Ask your data
//                   <br />

//                   <span className="bg-gradient-to-r from-white via-[#cbd5e1] to-[#7dd3fc] bg-clip-text text-transparent">
//                     anything.
//                   </span>

//                 </h1>


//                 <p className="mt-7 max-w-xl text-[15px] leading-7 text-[#858b95] sm:text-base">
//                   Turn natural-language questions into SQL queries, useful
//                   insights and visualizations. Explore your data without
//                   having to write SQL yourself.
//                 </p>


//                 {/* CTA */}
//                 <div className="mt-9 flex flex-col gap-3 sm:flex-row">

//                   <button
//                     onClick={onTryFree}
//                     className="group flex items-center justify-center gap-2.5 rounded-lg bg-white px-6 py-3.5 text-sm font-semibold text-[#101114] shadow-[0_8px_30px_rgba(255,255,255,0.08)] transition-all duration-200 hover:bg-[#f1f3f5] hover:shadow-[0_12px_40px_rgba(255,255,255,0.12)]"
//                   >
//                     <Zap className="h-4 w-4 text-[#2563eb]" />

//                     Try for free

//                     <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
//                   </button>


//                   {!user && googleClientId && (

//                     <div className="rounded-lg border border-white/[0.09] bg-white/[0.025] p-0.5">

//                       <GoogleLogin
//                         onSuccess={onGoogleSuccess}
//                         onError={onGoogleError}
//                         theme="filled_black"
//                         shape="rectangular"
//                         size="large"
//                         text="signin_with"
//                       />

//                     </div>

//                   )}

//                 </div>


//                 {/* Trust */}
//                 <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3">

//                   <div className="flex items-center gap-2 text-[10px] text-[#666c75]">
//                     <ShieldCheck className="h-3.5 w-3.5 text-emerald-400/80" />
//                     Secure authentication
//                   </div>

//                   <div className="flex items-center gap-2 text-[10px] text-[#666c75]">
//                     <Database className="h-3.5 w-3.5 text-blue-400/80" />
//                     SQLite & custom data
//                   </div>

//                   <div className="flex items-center gap-2 text-[10px] text-[#666c75]">
//                     <Activity className="h-3.5 w-3.5 text-violet-400/80" />
//                     Usage telemetry
//                   </div>

//                 </div>

//               </div>


//               {/* ================================================= */}
//               {/* PRODUCT PREVIEW */}
//               {/* ================================================= */}

//               <div className="relative">

//                 <div className="absolute -inset-8 rounded-[30px] bg-blue-500/[0.05] blur-3xl" />

//                 <div className="relative overflow-hidden rounded-2xl border border-white/[0.1] bg-[#101216] shadow-[0_30px_100px_rgba(0,0,0,0.45)]">

//                   {/* App header */}
//                   <div className="flex h-12 items-center justify-between border-b border-white/[0.07] px-4">

//                     <div className="flex items-center gap-1.5">
//                       <span className="h-2.5 w-2.5 rounded-full bg-[#383c43]" />
//                       <span className="h-2.5 w-2.5 rounded-full bg-[#383c43]" />
//                       <span className="h-2.5 w-2.5 rounded-full bg-[#383c43]" />
//                     </div>

//                     <div className="flex items-center gap-2 rounded-md border border-white/[0.06] bg-white/[0.025] px-3 py-1.5">
//                       <Database className="h-3 w-3 text-[#707680]" />
//                       <span className="text-[9px] text-[#777d87]">
//                         ecommerce.db
//                       </span>
//                     </div>

//                     <div className="h-5 w-14 rounded bg-white/[0.025]" />

//                   </div>


//                   {/* Workspace */}
//                   <div className="grid lg:grid-cols-[0.85fr_1.5fr]">

//                     {/* Left */}
//                     <div className="border-b border-white/[0.07] p-5 lg:border-b-0 lg:border-r">

//                       <div className="mb-5 flex items-center justify-between">

//                         <div>
//                           <p className="text-[10px] font-semibold text-[#c9ccd1]">
//                             Ask your data
//                           </p>
//                           <p className="mt-1 text-[8px] text-[#626771]">
//                             Natural language
//                           </p>
//                         </div>

//                         <Sparkles className="h-3.5 w-3.5 text-blue-400" />

//                       </div>


//                       <div className="rounded-xl border border-white/[0.07] bg-[#0b0d11] p-4">

//                         <p className="text-[10px] leading-5 text-[#9da2aa]">
//                           What is the total revenue generated by each product
//                           category?
//                         </p>

//                       </div>


//                       <div className="mt-4 flex items-center gap-2 text-[8px] text-[#626771]">

//                         <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />

//                         Query ready

//                       </div>

//                     </div>


//                     {/* Right */}
//                     <div className="p-5">

//                       <div className="mb-5 flex items-center justify-between">

//                         <div>
//                           <p className="text-[10px] font-semibold text-[#c9ccd1]">
//                             Revenue by category
//                           </p>

//                           <p className="mt-1 text-[8px] text-[#626771]">
//                             Generated from your database
//                           </p>
//                         </div>

//                         <span className="rounded-md bg-emerald-400/[0.07] px-2 py-1 text-[8px] font-medium text-emerald-400">
//                           Completed
//                         </span>

//                       </div>


//                       {/* Chart */}
//                       <div className="relative flex h-40 items-end gap-3 overflow-hidden rounded-xl border border-white/[0.06] bg-[#0b0d11] px-5 pb-5 pt-5">

//                         {/* horizontal lines */}
//                         <div className="absolute inset-x-5 top-8 border-t border-white/[0.035]" />
//                         <div className="absolute inset-x-5 top-16 border-t border-white/[0.035]" />
//                         <div className="absolute inset-x-5 top-24 border-t border-white/[0.035]" />
//                         <div className="absolute inset-x-5 top-32 border-t border-white/[0.035]" />

//                         <div className="relative flex h-full w-full items-end gap-2.5">

//                           <div className="h-[32%] flex-1 rounded-t bg-blue-500/30" />
//                           <div className="h-[48%] flex-1 rounded-t bg-blue-500/40" />
//                           <div className="h-[40%] flex-1 rounded-t bg-blue-500/35" />
//                           <div className="h-[70%] flex-1 rounded-t bg-blue-500/55" />
//                           <div className="h-[57%] flex-1 rounded-t bg-blue-500/45" />
//                           <div className="h-[88%] flex-1 rounded-t bg-blue-500/75" />

//                         </div>

//                       </div>


//                       {/* Results */}
//                       <div className="mt-4 grid grid-cols-3 gap-2">

//                         {[
//                           ["Electronics", "$42.8k"],
//                           ["Clothing", "$34.4k"],
//                           ["Home", "$26.1k"]
//                         ].map(([name, value]) => (

//                           <div
//                             key={name}
//                             className="rounded-lg border border-white/[0.06] bg-[#0b0d11] p-3"
//                           >

//                             <p className="truncate text-[8px] text-[#626771]">
//                               {name}
//                             </p>

//                             <p className="mt-1 text-[10px] font-semibold text-[#c9ccd1]">
//                               {value}
//                             </p>

//                           </div>

//                         ))}

//                       </div>

//                     </div>

//                   </div>

//                 </div>

//               </div>

//             </div>

//           </div>

//         </section>


//         {/* ========================================================= */}
//         {/* TRUST / VALUE STRIP */}
//         {/* ========================================================= */}

//         <section className="border-b border-white/[0.06] bg-[#0b0c0f]">

//           <div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-white/[0.06] sm:grid-cols-4">

//             {[
//               ["Natural Language", "Ask questions without SQL"],
//               ["Self-Healing", "Automatic query correction"],
//               ["Visual Results", "Charts from your data"],
//               ["Observable", "Tokens, latency & cost"]
//             ].map(([title, text]) => (

//               <div
//                 key={title}
//                 className="px-5 py-8 sm:px-8"
//               >

//                 <p className="text-xs font-semibold text-[#d0d3d8]">
//                   {title}
//                 </p>

//                 <p className="mt-1.5 text-[10px] leading-4 text-[#60656e]">
//                   {text}
//                 </p>

//               </div>

//             ))}

//           </div>

//         </section>


//         {/* ========================================================= */}
//         {/* HOW IT WORKS */}
//         {/* ========================================================= */}

//         <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32">

//           <div className="grid gap-14 lg:grid-cols-[0.8fr_1.2fr]">

//             <div>

//               <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-400">
//                 How it works
//               </p>

//               <h2 className="mt-4 text-3xl font-semibold tracking-[-0.035em] text-white sm:text-4xl">
//                 From a question
//                 <br />
//                 to an answer.
//               </h2>

//               <p className="mt-5 max-w-md text-sm leading-6 text-[#747a84]">
//                 The entire process happens automatically. You ask the
//                 question, and the system handles the SQL generation,
//                 validation and analysis.
//               </p>

//             </div>


//             <div className="overflow-hidden rounded-xl border border-white/[0.08]">

//               {[
//                 {
//                   number: "01",
//                   icon: Sparkles,
//                   title: "Ask",
//                   text: "Describe what you want to know using natural language."
//                 },
//                 {
//                   number: "02",
//                   icon: BrainCircuit,
//                   title: "Generate",
//                   text: "AI understands your database schema and generates SQL."
//                 },
//                 {
//                   number: "03",
//                   icon: ShieldCheck,
//                   title: "Validate",
//                   text: "The query is checked and repaired when necessary."
//                 },
//                 {
//                   number: "04",
//                   icon: BarChart3,
//                   title: "Understand",
//                   text: "Get results, summaries and useful visualizations."
//                 }
//               ].map((step, index) => {

//                 const Icon = step.icon;

//                 return (
//                   <div
//                     key={step.number}
//                     className={`group flex gap-5 p-6 transition hover:bg-white/[0.025] ${
//                       index !== 0 ? "border-t border-white/[0.07]" : ""
//                     }`}
//                   >

//                     <span className="pt-0.5 font-mono text-[10px] text-[#555b65]">
//                       {step.number}
//                     </span>

//                     <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-white/[0.07] bg-white/[0.025]">
//                       <Icon className="h-3.5 w-3.5 text-[#8b919b]" />
//                     </div>

//                     <div>
//                       <h3 className="text-xs font-semibold text-[#d5d8dc]">
//                         {step.title}
//                       </h3>

//                       <p className="mt-1.5 text-[11px] leading-5 text-[#626872]">
//                         {step.text}
//                       </p>
//                     </div>

//                   </div>
//                 );

//               })}

//             </div>

//           </div>

//         </section>


//         {/* ========================================================= */}
//         {/* FEATURES */}
//         {/* ========================================================= */}

//         <section className="border-y border-white/[0.06] bg-[#0b0c0f]">

//           <div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32">

//             <div className="max-w-2xl">

//               <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-400">
//                 Capabilities
//               </p>

//               <h2 className="mt-4 text-3xl font-semibold tracking-[-0.035em] text-white sm:text-4xl">
//                 Built around your data.
//               </h2>

//               <p className="mt-4 text-sm leading-6 text-[#707680]">
//                 Everything needed to go from an everyday question to a useful
//                 data-driven answer.
//               </p>

//             </div>


//             <div className="mt-12 grid overflow-hidden rounded-xl border border-white/[0.08] md:grid-cols-2">

//               {features.map((feature, index) => {

//                 const Icon = feature.icon;

//                 return (
//                   <div
//                     key={feature.title}
//                     className={`group p-8 transition hover:bg-white/[0.025] sm:p-10 ${
//                       index % 2 !== 0 ? "md:border-l border-white/[0.08]" : ""
//                     } ${
//                       index >= 2 ? "border-t border-white/[0.08]" : ""
//                     }`}
//                   >

//                     <div className="flex h-10 w-10 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.025]">
//                       <Icon className="h-4 w-4 text-[#9da3ad]" />
//                     </div>

//                     <h3 className="mt-6 text-sm font-semibold text-white">
//                       {feature.title}
//                     </h3>

//                     <p className="mt-3 max-w-md text-xs leading-6 text-[#696f78]">
//                       {feature.description}
//                     </p>

//                     <div className="mt-5 flex items-center gap-1.5 text-[9px] font-medium text-[#4e545d] transition group-hover:text-blue-400">
//                       Learn more
//                       <ArrowRight className="h-3 w-3 transition-transform group-hover:translate-x-1" />
//                     </div>

//                   </div>
//                 );

//               })}

//             </div>

//           </div>

//         </section>


//         {/* ========================================================= */}
//         {/* DATA IMPORT */}
//         {/* ========================================================= */}

//         <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32">

//           <div className="grid items-center gap-16 lg:grid-cols-2">

//             <div>

//               <div className="mb-5 flex h-10 w-10 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.025]">
//                 <Database className="h-4 w-4 text-[#9da3ad]" />
//               </div>

//               <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#666c75]">
//                 Your datasets
//               </p>

//               <h2 className="mt-4 text-3xl font-semibold tracking-[-0.035em] text-white sm:text-4xl">
//                 Use the data
//                 <br />
//                 you already have.
//               </h2>

//               <p className="mt-5 max-w-lg text-sm leading-7 text-[#707680]">
//                 Upload CSV, Excel or JSON files and turn them into queryable
//                 SQLite tables without setting up a database manually.
//               </p>

//               <div className="mt-7 flex gap-2">

//                 {["CSV", "XLSX", "JSON"].map((type) => (

//                   <span
//                     key={type}
//                     className="rounded-md border border-white/[0.08] bg-white/[0.025] px-3 py-1.5 font-mono text-[9px] text-[#7b818a]"
//                   >
//                     {type}
//                   </span>

//                 ))}

//               </div>

//             </div>


//             {/* Dataset card */}
//             <div className="rounded-xl border border-white/[0.08] bg-[#0d0f13] p-5 shadow-2xl">

//               <div className="flex items-center justify-between border-b border-white/[0.07] pb-4">

//                 <div className="flex items-center gap-2">
//                   <Layers className="h-3.5 w-3.5 text-[#7c828c]" />
//                   <span className="text-[10px] font-semibold text-[#c1c5ca]">
//                     ecommerce.csv
//                   </span>
//                 </div>

//                 <span className="text-[9px] text-[#555b64]">
//                   1,284 rows
//                 </span>

//               </div>


//               <div className="py-5">

//                 <div className="mb-3 flex items-center justify-between">

//                   <span className="font-mono text-[10px] text-[#c1c5ca]">
//                     products
//                   </span>

//                   <span className="text-[8px] text-[#555b64]">
//                     SQLite table
//                   </span>

//                 </div>


//                 <div className="space-y-1.5">

//                   {[
//                     ["product_name", "TEXT"],
//                     ["category", "TEXT"],
//                     ["price", "REAL"],
//                     ["stock", "INTEGER"]
//                   ].map(([name, type]) => (

//                     <div
//                       key={name}
//                       className="flex items-center justify-between rounded-md border border-white/[0.04] bg-white/[0.02] px-3 py-2.5"
//                     >

//                       <span className="font-mono text-[9px] text-[#858b94]">
//                         {name}
//                       </span>

//                       <span className="font-mono text-[8px] text-[#4f555e]">
//                         {type}
//                       </span>

//                     </div>

//                   ))}

//                 </div>

//               </div>

//             </div>

//           </div>

//         </section>


//         {/* ========================================================= */}
//         {/* EXAMPLES */}
//         {/* ========================================================= */}

//         <section className="border-y border-white/[0.06] bg-[#0b0c0f]">

//           <div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32">

//             <div className="mb-10">

//               <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-400">
//                 Examples
//               </p>

//               <h2 className="mt-4 text-3xl font-semibold tracking-[-0.035em] text-white sm:text-4xl">
//                 Just ask a question.
//               </h2>

//             </div>


//             <div className="grid gap-3 md:grid-cols-2">

//               {sampleQueries.map((query) => (

//                 <button
//                   key={query}
//                   onClick={onTryFree}
//                   className="group flex items-center justify-between gap-5 rounded-xl border border-white/[0.07] bg-[#101216] p-5 text-left transition hover:border-white/[0.14] hover:bg-[#13161a]"
//                 >

//                   <div className="flex items-start gap-3">

//                     <div className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-blue-500/[0.08]">
//                       <Sparkles className="h-3 w-3 text-blue-400" />
//                     </div>

//                     <span className="text-xs leading-5 text-[#858b94] transition group-hover:text-[#c0c4c9]">
//                       {query}
//                     </span>

//                   </div>

//                   <ArrowRight className="h-3.5 w-3.5 shrink-0 text-[#4e545c] transition group-hover:translate-x-1 group-hover:text-blue-400" />

//                 </button>

//               ))}

//             </div>

//           </div>

//         </section>


//         {/* ========================================================= */}
//         {/* OBSERVABILITY */}
//         {/* ========================================================= */}

//         <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32">

//           <div className="grid items-center gap-14 lg:grid-cols-[1fr_0.9fr]">

//             <div>

//               <div className="mb-5 flex h-10 w-10 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.025]">
//                 <DollarSign className="h-4 w-4 text-[#9da3ad]" />
//               </div>

//               <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#666c75]">
//                 Observability
//               </p>

//               <h2 className="mt-4 max-w-xl text-3xl font-semibold tracking-[-0.035em] text-white sm:text-4xl">
//                 See what every query uses.
//               </h2>

//               <p className="mt-5 max-w-lg text-sm leading-7 text-[#707680]">
//                 Track token usage, latency, estimated cost and retries for
//                 authenticated users through your Langfuse integration.
//               </p>

//               <div className="mt-7 flex items-center gap-2 text-[10px] text-[#676d76]">
//                 <Check className="h-3.5 w-3.5 text-emerald-400" />
//                 Per-user query history
//               </div>

//               <div className="mt-2 flex items-center gap-2 text-[10px] text-[#676d76]">
//                 <Check className="h-3.5 w-3.5 text-emerald-400" />
//                 Token and cost estimates
//               </div>

//             </div>


//             <div className="grid grid-cols-2 overflow-hidden rounded-xl border border-white/[0.08]">

//               {[
//                 ["Tokens", "12.4K"],
//                 ["Latency", "1.24s"],
//                 ["Est. cost", "$0.014"],
//                 ["Retries", "1"]
//               ].map(([label, value]) => (

//                 <div
//                   key={label}
//                   className="border-b border-r border-white/[0.07] bg-[#0d0f13] p-6 last:border-0"
//                 >

//                   <p className="text-[9px] uppercase tracking-[0.15em] text-[#555b64]">
//                     {label}
//                   </p>

//                   <p className="mt-3 text-2xl font-semibold tracking-tight text-[#d8dbe0]">
//                     {value}
//                   </p>

//                 </div>

//               ))}

//             </div>

//           </div>

//         </section>


//         {/* ========================================================= */}
//         {/* FINAL CTA */}
//         {/* ========================================================= */}

//         <section className="relative border-t border-white/[0.07]">

//           <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-blue-500/[0.035] to-transparent" />

//           <div className="relative mx-auto max-w-3xl px-5 py-28 text-center sm:px-8 sm:py-36">

//             <div className="mx-auto flex h-11 w-11 items-center justify-center rounded-xl border border-white/[0.08] bg-white/[0.035]">
//               <Sparkles className="h-4 w-4 text-blue-400" />
//             </div>

//             <h2 className="mt-7 text-4xl font-semibold tracking-[-0.045em] text-white sm:text-5xl">
//               Your data is waiting.
//             </h2>

//             <p className="mx-auto mt-5 max-w-lg text-sm leading-6 text-[#707680]">
//               Ask your first question and see what TextQuery can find.
//             </p>

//             <button
//               onClick={onTryFree}
//               className="group mt-8 inline-flex items-center gap-2.5 rounded-lg bg-white px-6 py-3.5 text-sm font-semibold text-[#101114] transition hover:bg-[#e9ebed]"
//             >
//               Try for free
//               <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
//             </button>

//           </div>

//         </section>

//       </main>


//       {/* ========================================================= */}
//       {/* FOOTER */}
//       {/* ========================================================= */}

//       <footer className="border-t border-white/[0.07] bg-[#060709]">

//         <div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-7 sm:flex-row sm:items-center sm:justify-between sm:px-8">

//           <div className="flex items-center gap-2.5">

//             <div className="flex h-7 w-7 items-center justify-center rounded-md bg-white text-[#08090b]">
//               <Database className="h-3.5 w-3.5" />
//             </div>

//             <span className="text-xs font-semibold text-[#bfc3c8]">
//               TextQuery
//             </span>

//           </div>

//           <p className="text-[10px] text-[#4f555e]">
//             Natural language analytics for your data.
//           </p>

//         </div>

//       </footer>

//     </div>
//   );
// }
