import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Send,
  Zap,
  AlertCircle,
  BrainCircuit,
  UserCheck,
  Info,
  DollarSign
} from 'lucide-react';
import { Navigation } from './components/Navigation';
import { LandingPage } from './components/LandingPage';
import { UserDashboard } from './components/UserDashboard';
import { SqlCodeBlock } from './components/SqlCodeBlock';
import { VisualizerCard } from './components/VisualizerCard';
import { DataTable } from './components/DataTable';
import { AgentWorkflowTracker } from './components/AgentWorkflowTracker';
import { SchemaBrowser } from './components/SchemaBrowser';
import { SqlPlayground } from './components/SqlPlayground';
import { DatasetUploadModal } from './components/DatasetUploadModal';

export function App() {
  const [activeTab, setActiveTab] = useState(() => {
    const token = localStorage.getItem('text2sql_auth_token');
    return token ? 'agent' : 'landing';
  });
  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(false);
  const [activeResultTab, setActiveResultTab] = useState('viz'); // 'viz' | 'data' | 'sql'
  const [currentResult, setCurrentResult] = useState(null);
  const [error, setError] = useState(null);
  const [history, setHistory] = useState([]);
  const [health, setHealth] = useState(null);
  const [schemaData, setSchemaData] = useState(null);
  const [resettingDb, setResettingDb] = useState(false);
  const [isUploadOpen, setIsUploadOpen] = useState(false);

  // User Auth State
  const [user, setUser] = useState(null);
  const [authToken, setAuthToken] = useState(localStorage.getItem('text2sql_auth_token') || null);

  const googleClientId = import.meta.env.VITE_GOOGLE_CLIENT_ID;

  // Starters
  const starters = [
    { title: "Total Revenue by Category", query: "What is the total revenue generated by each product category?" },
    { title: "Top 3 Customers", query: "Show the top 3 customers who spent the most money and their countries." },
    { title: "Order Status Breakdown", query: "Give me the count and total order value for each order status." },
    { title: "Low Stock Inventory", query: "Which products have low stock (< 35 items) and their prices?" }
  ];

  // Fetch initial health, schema, and user session
  useEffect(() => {
    fetchHealth();
    fetchSchema();
    if (authToken) {
      verifyUserSession(authToken);
    }
  }, []);

  useEffect(() => {
    if (activeTab !== 'import-data') {
      setIsUploadOpen(false);
    }
  }, [activeTab]);


  const fetchHealth = async () => {
    try {
      const res = await fetch('/api/health');
      if (res.ok) {
        const data = await res.json();
        setHealth(data);
      }
    } catch (e) {
      console.warn("Backend health check warning:", e);
    }
  };

  const fetchSchema = async () => {
    try {
      const res = await fetch('/api/schema');
      if (res.ok) {
        const data = await res.json();
        setSchemaData(data);
      }
    } catch (e) {
      console.warn("Schema fetch warning:", e);
    }
  };

  const verifyUserSession = async (token) => {
    try {
      const res = await fetch(`/api/auth/me?token=${encodeURIComponent(token)}`);

      if (res.ok) {
        const data = await res.json();
        setUser(data.user);
        setActiveTab('agent');
      } else {
        localStorage.removeItem('text2sql_auth_token');
        setAuthToken(null);
        setUser(null);
        setActiveTab('landing');
      }
    } catch (e) {
      console.warn("Session restore error:", e);
    }
  };

  const handleGoogleSuccess = async (credentialResponse) => {
    try {
      const res = await fetch('/api/auth/google', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ credential: credentialResponse.credential })
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.detail || 'Google Authentication failed');
      }
      setUser(data.user);
      setAuthToken(data.token);
      localStorage.setItem('text2sql_auth_token', data.token);
      setActiveTab('agent');
    } catch (err) {
      alert(`Login failed: ${err.message}`);
    }
  };

  const handleGoogleError = () => {
    alert("Google Sign-In was unsuccessful. Please try again.");
  };

  const handleSignOut = () => {
    setUser(null);
    setAuthToken(null);
    localStorage.removeItem('text2sql_auth_token');
    setActiveTab('landing');
  };

  const handleResetDb = async () => {
    setResettingDb(true);
    try {
      const res = await fetch('/api/reset-db', { method: 'POST' });
      if (res.ok) {
        await fetchSchema();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setResettingDb(false);
    }
  };

  const handleUploadSuccess = async () => {
    await fetchSchema();
    setActiveTab('schema');
  };

  const handleSubmit = async (overrideQuery = null, isGuestMode = false) => {
    const queryText = (typeof overrideQuery === 'string' ? overrideQuery : question).trim();
    if (!queryText) return;

    setLoading(true);
    setError(null);

    const payload = {
      question: queryText,
      user_id: isGuestMode ? null : user?.id,
      guest_mode: isGuestMode || !user
    };

    try {
      const res = await fetch('/api/query', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.detail || 'Query execution failed');
      }
      setCurrentResult(data);
      if (data.chart_type === 'table') {
        setActiveResultTab('data');
      } else {
        setActiveResultTab('viz');
      }
      setHistory(prev => [data, ...prev]);
    } catch (err) {
      setError(err.message);
      setCurrentResult(null);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#090d16] text-slate-100 flex flex-col selection:bg-indigo-500 selection:text-white">
      {/* Background ambient light */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none z-0">
        <div className="absolute -top-40 -left-40 w-96 h-96 bg-indigo-600/15 rounded-full blur-[128px]"></div>
        <div className="absolute top-1/3 -right-40 w-96 h-96 bg-purple-600/15 rounded-full blur-[128px]"></div>
        <div className="absolute -bottom-40 left-1/3 w-96 h-96 bg-cyan-600/10 rounded-full blur-[128px]"></div>
      </div>

      {/* Upload Modal */}
      <DatasetUploadModal
        isOpen={isUploadOpen}
        onClose={() => setIsUploadOpen(false)}
        onUploadSuccess={handleUploadSuccess}
      />

      {/* Top Navbar */}
      <Navigation
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        health={health}
        historyCount={history.length}
        onOpenUpload={() => setIsUploadOpen(true)}
        user={user}
        onGoogleSuccess={handleGoogleSuccess}
        onGoogleError={handleGoogleError}
        onSignOut={handleSignOut}
        googleClientId={googleClientId}
      />

      {/* Main Content Area */}
      <main
        className={`flex-1 w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 relative z-10 ${user ? 'ml-[250px] max-w-[calc(100%-250px)]' : 'max-w-7xl'
          }`}
      >
        {/* ROUTE 1: LANDING PAGE */}
        {activeTab === 'landing' && (
          <LandingPage
            onTryFree={() => setActiveTab('guest')}
            onGoogleSuccess={handleGoogleSuccess}
            onGoogleError={handleGoogleError}
            user={user}
            googleClientId={googleClientId}
          />
        )}

        {/* ROUTE 2: TRY FOR FREE (GUEST MODE) */}
        {activeTab === 'guest' && (
          <div className="space-y-8">
            {/* Banner */}
            <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <Info className="w-5 h-5 text-amber-400 shrink-0" />
                <p className="text-xs text-amber-200">
                  <span className="font-bold">Guest Mode Sandbox:</span> Queries execute freely without account login. Queries in guest mode are <u>not tracked in Langfuse</u>.
                </p>
              </div>
              {!user && (
                <button
                  onClick={() => setActiveTab('landing')}
                  className="px-3 py-1.5 rounded-lg bg-amber-500 text-slate-950 font-bold text-xs hover:bg-amber-400 transition"
                >
                  Sign in with Google
                </button>
              )}
            </div>

            {/* Guest Input */}
            <div className="relative rounded-3xl p-8 border border-slate-800 bg-slate-900/60 shadow-xl space-y-6">
              <h2 className="text-2xl font-extrabold text-white flex items-center gap-2">
                <Zap className="w-5 h-5 text-amber-400" />
                Free Text2SQL Sandbox
              </h2>

              <div className="relative flex items-center shadow-2xl rounded-2xl glass-panel border border-slate-700/60 p-2 focus-within:border-cyan-500 transition-all">
                <Sparkles className="w-5 h-5 text-cyan-400 ml-3 mr-2 shrink-0 animate-pulse" />
                <input
                  type="text"
                  value={question}
                  onChange={(e) => setQuestion(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && !loading && handleSubmit(question, true)}
                  placeholder="Ask any database question (e.g. List top 5 selling products)..."
                  className="w-full bg-transparent text-sm text-white placeholder-slate-500 focus:outline-none px-2 py-2"
                />
                <button
                  onClick={() => handleSubmit(question, true)}
                  disabled={loading || !question.trim()}
                  className="flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400 text-slate-950 font-bold text-xs shadow-lg transition disabled:opacity-40"
                >
                  {loading ? 'Executing...' : 'Run Query'}
                  <Send className="w-3.5 h-3.5" />
                </button>
              </div>

              {/* Starters */}
              <div className="flex flex-wrap gap-2">
                {starters.map((item, idx) => (
                  <button
                    key={idx}
                    onClick={() => {
                      setQuestion(item.query);
                      handleSubmit(item.query, true);
                    }}
                    className="px-3 py-1.5 rounded-lg bg-slate-800/80 border border-slate-700 text-xs text-slate-300 hover:text-white transition"
                  >
                    {item.title}
                  </button>
                ))}
              </div>
            </div>

            {/* Results display */}
            {currentResult && (
              <div className="space-y-6">
                <AgentWorkflowTracker
                  latency={currentResult.latency}
                  retryCount={currentResult.retry_count}
                  repairHistory={currentResult.repair_history}
                  isValid={currentResult.is_valid}
                  error={currentResult.error_message}
                />
                {currentResult.df_result && currentResult.df_result.length > 0 && (
                  <DataTable data={currentResult.df_result} columns={currentResult.columns} />
                )}
              </div>
            )}
          </div>
        )}

        {/* ROUTE 3: AI QUERY STUDIO (AUTHENTICATED & TRACKED) */}
        {activeTab === 'agent' && (
          <div className="space-y-8">
            {/* User status info banner */}
            {user ? (
              <div className="p-3.5 rounded-2xl bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-between text-xs text-indigo-300">
                <div className="flex items-center gap-2">
                  <UserCheck className="w-4 h-4 text-emerald-400" />
                  <span>Authenticated User: <strong>{user.name}</strong> (#{user.id}). Langfuse Cost Telemetry active.</span>
                </div>
                <button onClick={() => setActiveTab('dashboard')} className="text-cyan-400 hover:underline font-semibold">
                  View My Dashboard →
                </button>
              </div>
            ) : (
              <div className="p-3.5 rounded-2xl bg-slate-900 border border-slate-800 flex items-center justify-between text-xs text-slate-400">
                <span>Sign in with Google to enable personal cost tracking &amp; history dashboard.</span>
              </div>
            )}

            {/* Query Hero Banner */}
            <div className="relative rounded-3xl p-8 border border-slate-800/80 bg-gradient-to-b from-slate-900/80 via-slate-900/40 to-slate-950/80 backdrop-blur-xl shadow-2xl space-y-6">
              <div className="max-w-3xl">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-semibold mb-3">
                  <BrainCircuit className="w-3.5 h-3.5" />
                  LangGraph Autonomous SQL Multi-Agent
                </div>
                <h1 className="text-3xl font-extrabold tracking-tight text-white leading-tight">
                  Turn plain English into <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-indigo-300 to-purple-400">executable SQL</span> with cost telemetry.
                </h1>
              </div>

              {/* Input */}
              <div className="relative flex items-center shadow-2xl rounded-2xl glass-panel border border-slate-700/60 p-2 focus-within:border-cyan-500 transition-all">
                <Sparkles className="w-5 h-5 text-cyan-400 ml-3 mr-2 shrink-0 animate-pulse" />
                <input
                  type="text"
                  value={question}
                  onChange={(e) => setQuestion(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && !loading && handleSubmit(question, false)}
                  placeholder="e.g. Which customers spent over $200 and what did they purchase?"
                  className="w-full bg-transparent text-sm sm:text-base text-white placeholder-slate-500 focus:outline-none px-2 py-2"
                />
                <button
                  onClick={() => handleSubmit(question, false)}
                  disabled={loading || !question.trim()}
                  className="flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-indigo-600 via-blue-600 to-cyan-500 hover:from-indigo-500 hover:to-cyan-400 text-white font-semibold text-xs sm:text-sm shadow-lg shadow-indigo-500/25 transition disabled:opacity-40 shrink-0"
                >
                  {loading ? 'Running...' : 'Run Query'}
                  <Send className="w-3.5 h-3.5" />
                </button>
              </div>

              {/* Starters */}
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-xs text-slate-400 flex items-center gap-1 font-medium">
                  <Zap className="w-3.5 h-3.5 text-amber-400" />
                  Quick Presets:
                </span>
                {starters.map((item, idx) => (
                  <button
                    key={idx}
                    onClick={() => {
                      setQuestion(item.query);
                      handleSubmit(item.query, false);
                    }}
                    className="px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-xs text-slate-300 hover:text-cyan-300 hover:border-slate-700 transition"
                  >
                    {item.title}
                  </button>
                ))}
              </div>
            </div>

            {/* Error view */}
            {error && (
              <div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs flex items-center gap-3">
                <AlertCircle className="w-5 h-5 shrink-0" />
                <span>{error}</span>
              </div>
            )}

            {/* Result display */}
            {currentResult && (
              <div className="space-y-8">
                {/* User Token & Cost Telemetry Pill */}
                {currentResult.tokens && currentResult.tokens.total_tokens > 0 && (
                  <div className="p-4 rounded-2xl glass-panel border border-slate-800 flex flex-wrap items-center justify-between gap-4 text-xs">
                    <div className="flex items-center gap-3">
                      <div className="p-2 bg-purple-500/10 text-purple-400 rounded-lg">
                        <DollarSign className="w-4 h-4" />
                      </div>
                      <div>
                        <span className="font-semibold text-slate-200">Query Cost: </span>
                        <span className="font-mono text-purple-300 font-bold">${currentResult.tokens.cost_usd?.toFixed(6)} USD</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-6 text-slate-400">
                      <div>Tokens: <span className="font-mono text-cyan-300 font-bold">{currentResult.tokens.total_tokens}</span> (Prompt: {currentResult.tokens.prompt_tokens} | Compl: {currentResult.tokens.completion_tokens})</div>
                      <div>Langfuse Trace: <span className="font-mono text-indigo-400">{currentResult.trace_id}</span></div>
                    </div>
                  </div>
                )}

                {/* Workflow Tracker */}
                <AgentWorkflowTracker
                  latency={currentResult.latency}
                  retryCount={currentResult.retry_count}
                  repairHistory={currentResult.repair_history}
                  isValid={currentResult.is_valid}
                  error={currentResult.error_message}
                />

                {/* Results Navigation Tabs */}
                <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => setActiveResultTab('viz')}
                      className={`px-4 py-2 rounded-xl text-xs font-semibold transition ${activeResultTab === 'viz'
                        ? 'bg-indigo-600 text-white shadow-md'
                        : 'bg-slate-900 text-slate-400 hover:text-white'
                        }`}
                    >
                      BI Chart Visualization
                    </button>
                    <button
                      onClick={() => setActiveResultTab('data')}
                      className={`px-4 py-2 rounded-xl text-xs font-semibold transition ${activeResultTab === 'data'
                        ? 'bg-indigo-600 text-white shadow-md'
                        : 'bg-slate-900 text-slate-400 hover:text-white'
                        }`}
                    >
                      Data Table ({currentResult.row_count} rows)
                    </button>
                    <button
                      onClick={() => setActiveResultTab('sql')}
                      className={`px-4 py-2 rounded-xl text-xs font-semibold transition ${activeResultTab === 'sql'
                        ? 'bg-indigo-600 text-white shadow-md'
                        : 'bg-slate-900 text-slate-400 hover:text-white'
                        }`}
                    >
                      Generated SQL Code
                    </button>
                  </div>
                </div>

                {/* Tab Views */}
                {activeResultTab === 'viz' && (
                  <VisualizerCard
                    chartType={currentResult.chart_type}
                    chartConfig={currentResult.chart_config}
                    summary={currentResult.analyst_summary}
                    data={currentResult.df_result}
                  />
                )}

                {activeResultTab === 'data' && (
                  <DataTable data={currentResult.df_result} columns={currentResult.columns} />
                )}

                {activeResultTab === 'sql' && (
                  <SqlCodeBlock
                    code={currentResult.sql_query}
                    explanation={currentResult.analyst_summary}
                    repairHistory={currentResult.repair_history}
                  />
                )}
              </div>
            )}
          </div>
        )}

        {/* ROUTE 4: USER DASHBOARD & COSTS */}
        {activeTab === 'dashboard' && (
          <UserDashboard user={user} onRequireLogin={() => setActiveTab('landing')} />
        )}

        {/* ROUTE 5: DATABASE SCHEMA EXPLORER */}
        {activeTab === 'schema' && (
          <SchemaBrowser
            schemaData={schemaData}
            onResetDb={handleResetDb}
            resetting={resettingDb}
          />
        )}

        {/* ROUTE 6: DIRECT SQL PLAYGROUND */}
        {activeTab === 'console' && (
          <SqlPlayground />
        )}
      </main>
    </div>
  );
}
