import React, { useState, useEffect } from 'react';
import {
  Routes,
  Route,
  Navigate,
  useNavigate,
  useLocation,
} from 'react-router-dom';

import { Navigation } from './components/Navigation';
import { LandingPage } from './components/landing/LandingPage';
import { UserDashboard } from './components/UserDashboard';
import { SchemaBrowser } from './components/SchemaBrowser';
import { SqlPlayground } from './components/SqlPlayground';
import { DatasetUpload } from './components/DatasetUpload';
import { GuestPage } from './components/GuestPage';
import { QueryStudio } from './components/QueryStudio';
import { QueryHistory } from './components/QueryHistory';
import { ProtectedRoute } from './routes/ProtectedRoute';
import api from './api/axiosClient';

export function App() {
  const navigate = useNavigate();
  const location = useLocation();

  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(false);
  const [activeResultTab, setActiveResultTab] = useState('sql');
  const [currentResult, setCurrentResult] = useState(null);
  const [error, setError] = useState(null);
  const [history, setHistory] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [historyPagination, setHistoryPagination] = useState({
    page: 1,
    limit: 10,
    total: 0,
    total_pages: 0,
  });
  const [schemaData, setSchemaData] = useState(null);

  const [user, setUser] = useState(null);
  const [authToken, setAuthToken] = useState(
    localStorage.getItem('text2sql_auth_token') || null
  );

  const [activeSection, setActiveSection] = useState('home');
  const [pendingScroll, setPendingScroll] = useState(null);

  const googleClientId = import.meta.env.VITE_GOOGLE_CLIENT_ID;

  const starters = [
    {
      title: 'Total Revenue by Category',
      query:
        'What is the total revenue generated by each product category?',
    },
    {
      title: 'Top 3 Customers',
      query:
        'Show the top 3 customers who spent the most money and their countries.',
    },
    {
      title: 'Order Status Breakdown',
      query:
        'Give me the count and total order value for each order status.',
    },
    {
      title: 'Low Stock Inventory',
      query:
        'Which products have low stock (< 35 items) and their prices?',
    },
  ];

  useEffect(() => {
    fetchSchema();
  }, []);

  useEffect(() => {
    if (!authToken) {
      setUser(null);
      setHistory([]);
      return;
    }

    verifyUserSession();
  }, [authToken]);

  useEffect(() => {
    if (authToken && location.pathname === '/history') {
      fetchUserHistory(1);
    }
  }, [authToken, location.pathname]);

  const fetchUserHistory = async (page = 1) => {
    setHistoryLoading(true);
    try {
      const res = await api.get('/api/user/history', {
        params: {
          page,
          limit: 10,
        },
      });
      setHistory(res.data.history || []);
      setHistoryPagination(
        res.data.pagination || {
          page,
          limit: 10,
          total: 0,
          total_pages: 0,
        }
      );
    } catch (err) {
      console.warn('Failed to fetch user history:', err.message);
      setHistory([]);
    } finally {
      setHistoryLoading(false);
    }
  };

  const handleClearHistory = async () => {
    try {
      await api.delete('/api/user/history');
      setHistory([]);
      setHistoryPagination({
        page: 1,
        limit: 10,
        total: 0,
        total_pages: 0,
      });
    } catch (err) {
      console.error('Failed to clear history:', err.message);
    }
  };

  const handlePage = (page) => {
    if (
      page < 1 ||
      page > historyPagination.total_pages ||
      page === historyPagination.page
    ) {
      return;
    }

    fetchUserHistory(page);
  };

  const handleSelectHistoryItem = (item) => {
    setQuestion(item.question);
    setCurrentResult(item);
    if (item.chart_type === 'table' || item.chart_type === 'none') {
      setActiveResultTab('data');
    } else {
      setActiveResultTab('viz');
    }
    navigate('/query', {
      state: {
        fromHistory: true,
      },
    });
  };

  useEffect(() => {
    if (location.pathname === '/') {
      requestAnimationFrame(() => {
        scrollToId(pendingScroll);
        setPendingScroll(null);
      });
    }
  }, [location.pathname]);

  useEffect(() => {
    if ('scrollRestoration' in window.history) {
      window.history.scrollRestoration = 'manual';
    }
    window.scrollTo(0, 0);
  }, [location.pathname]);

  const fetchSchema = async () => {
    try {
      const res = await api.get('/api/schema');
      setSchemaData(res.data);
    } catch (error) {
      console.warn('Schema fetch warning:', error.response?.data?.detail || error.message);
    }
  };

  const verifyUserSession = async () => {
    try {
      const response = await api.get('/api/auth/me');
      setUser(response.data.user);
    } catch (error) {
      localStorage.removeItem('text2sql_auth_token');
      setAuthToken(null);
      setUser(null);
      console.warn(
        'Session restore error:',
        error.response?.data?.detail || error.message
      );
    }
  };

  const handleGoogleSuccess = async (credentialResponse) => {
    try {
      const payload = credentialResponse.credential
        ? { credential: credentialResponse.credential }
        : { access_token: credentialResponse.access_token };

      const response = await api.post('/api/auth/google', payload);

      const data = response.data;

      setUser(data.user);
      setAuthToken(data.token);
      localStorage.setItem('text2sql_auth_token', data.token);
      setQuestion('');
      setCurrentResult(null);
      setError(null);
      setActiveResultTab('viz');
      navigate('/query');
    } catch (error) {
      alert(
        `Login failed: ${error.response?.data?.detail ||
        error.message ||
        'Google Authentication failed'
        }`
      );
    }
  };

  const handleGoogleError = () => {
    alert(
      'Google Sign-In was unsuccessful. Please try again.'
    );
  };

  const handleSignOut = () => {
    setUser(null);
    setAuthToken(null);
    setQuestion('');
    setCurrentResult(null);
    setError(null);
    setSchemaData(null);
    localStorage.removeItem('text2sql_auth_token');
    navigate('/');
  };

  const scrollToId = (id) => {
    if (id === 'home') {
      window.scrollTo({
        top: 0,
        behavior: 'smooth',
      });
      return;
    }
    document
      .getElementById(id)
      ?.scrollIntoView({
        behavior: 'smooth',
        block: 'start',
      });
  };

  const handleNavigate = (id) => {
    setActiveSection(id);
    if (location.pathname !== '/') {
      setPendingScroll(id);
      navigate('/');
    } else {
      scrollToId(id);
    }
  };

  const handleUploadSuccess = async () => {
    await fetchSchema();
    navigate('/schema');
  };

  const handleDeleteTable = async (tableName) => {
    try {
      await api.delete('/api/table', {
        data: { table_name: tableName },
      });
      await fetchSchema();
    } catch (error) {
      console.error('Delete table error:', error);
      alert(
        error.response?.data?.detail ||
        'Failed to delete table. Please try again.'
      );
    }
  };

  const handleSubmit = async (
    overrideQuery = null,
    isGuestMode = false
  ) => {
    const queryText = (
      typeof overrideQuery === 'string'
        ? overrideQuery
        : question
    ).trim();
    if (!queryText) return;
    setLoading(true);
    setError(null);
    const payload = {
      question: queryText,
      user_id: isGuestMode ? null : user?.id,
      guest_mode: isGuestMode || !user,
    };
    try {
      const response = await api.post('/api/query', payload);
      const data = response.data;
      setCurrentResult(data);
      if (data.chart_type === 'table') {
        setActiveResultTab('data');
      } else {
        setActiveResultTab('viz');
      }
      if (!isGuestMode && user) {
        fetchUserHistory(1);
      }
    } catch (err) {
      setError(err.message);
      setCurrentResult(null);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#090d16] text-slate-100 flex flex-col selection:bg-indigo-500 selection:text-white">
      {location.pathname === '/' && (
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="absolute left-1/2 top-[-220px] h-[850px] w-[900px] -translate-x-1/2 rounded-full bg-blue-600/[0.08] blur-[130px]" />
          <div className="absolute left-[15%] top-[350px] h-[300px] w-[300px] rounded-full bg-cyan-500/[0.035] blur-[100px]" />
          <div className="absolute right-[5%] top-[500px] h-[350px] w-[350px] rounded-full bg-violet-500/[0.035] blur-[120px]" />
          <div
            className="absolute inset-0 opacity-[0.025]"
            style={{
              backgroundImage:
                'linear-gradient(rgba(255,255,255,0.7) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.7) 1px, transparent 1px)',
              backgroundSize: '64px 64px',
            }}
          />
        </div>
      )}
      <Navigation
        activeTab={location.pathname}
        activeSection={activeSection}
        onNavigate={handleNavigate}
        user={user}
        onGoogleSuccess={handleGoogleSuccess}
        onGoogleError={handleGoogleError}
        onSignOut={handleSignOut}
        googleClientId={googleClientId}
      />
      <main
        className={`flex-1 w-full min-w-0 mx-auto px-4 sm:px-6 lg:px-8 pt-8 relative z-10 ${user
          ? 'ml-0 max-w-full lg:ml-[250px] lg:max-w-[calc(100%-250px)]'
          : 'max-w-7xl'
          }`}
      >
        <Routes>
          <Route
            path="/"
            element={
              authToken ? (
                <Navigate to="/query" replace />
              ) : (
                <LandingPage
                  onTryFree={() => navigate('/guest')}
                />
              )
            }
          />
          <Route
            path="/guest"
            element={
              authToken ? (
                <Navigate to="/query" replace />
              ) : (
                <GuestPage
                  question={question}
                  setQuestion={setQuestion}
                  loading={loading}
                  error={error}
                  currentResult={currentResult}
                  setCurrentResult={setCurrentResult}
                  activeResultTab={activeResultTab}
                  setActiveResultTab={
                    setActiveResultTab
                  }
                  onSubmit={(q) =>
                    handleSubmit(q, true)
                  }
                  user={user}
                  starters={starters}
                  onGoogleSuccess={
                    handleGoogleSuccess
                  }
                  onGoogleError={
                    handleGoogleError
                  }
                  googleClientId={
                    googleClientId
                  }
                  schemaData={schemaData}
                />
              )
            }
          />
          <Route
            path="/query"
            element={
              <ProtectedRoute>
                <QueryStudio
                  question={question}
                  setQuestion={setQuestion}
                  loading={loading}
                  error={error}
                  currentResult={currentResult}
                  setCurrentResult={setCurrentResult}
                  activeResultTab={activeResultTab}
                  setActiveResultTab={setActiveResultTab}
                  onSubmit={(q) => handleSubmit(q, false)}
                  user={user}
                  starters={starters}
                  schemaData={schemaData}
                />
              </ProtectedRoute>
            }
          />
          <Route
            path="/dashboard"
            element={
              <ProtectedRoute>
                <UserDashboard
                  user={user}
                  onRequireLogin={() => navigate('/')}
                />
              </ProtectedRoute>
            }
          />
          <Route
            path="/schema"
            element={
              <ProtectedRoute>
                <SchemaBrowser
                  schemaData={schemaData}
                  onDelete={handleDeleteTable}
                />
              </ProtectedRoute>
            }
          />
          <Route
            path="/sql-console"
            element={
              <ProtectedRoute>
                <SqlPlayground />
              </ProtectedRoute>
            }
          />
          <Route
            path="/dataset"
            element={
              <ProtectedRoute>
                <DatasetUpload
                  onClose={() => navigate('/query')}
                  onUploadSuccess={handleUploadSuccess}
                />
              </ProtectedRoute>
            }
          />
          <Route
            path="/history"
            element={
              <ProtectedRoute>
                <QueryHistory
                  history={history}
                  historyLoading={historyLoading}
                  onSelectQuery={handleSelectHistoryItem}
                  onClearHistory={handleClearHistory}
                  pagination={historyPagination}
                  onPageChange={handlePage}
                />
              </ProtectedRoute>
            }
          />
          <Route
            path="*"
            element={
              <Navigate
                to={localStorage.getItem('text2sql_auth_token') ? '/query' : '/'}
                replace
              />
            }
          />
        </Routes>
      </main>
    </div>
  );
}