import React from 'react';
import {
  Sparkles,
  Database,
  ShieldCheck,
  BrainCircuit,
  Zap,
  ArrowRight,
  BarChart3,
  Activity,
} from 'lucide-react';

export default function HeroSection({
  onTryFree,
}) {
  return (
    <section id="home" className="border-b border-white/[0.06]">
      <div className="pb-20 pt-10 sm:pb-28 sm:pt-28 lg:pt-20">
        <div className="flex flex-col items-center gap-14 lg:flex-row lg:items-center lg:gap-20">
          <div>
            <h1 className="max-w-2xl text-[46px] font-semibold leading-[1.04] tracking-[-0.045em] text-white sm:text-6xl lg:text-[70px]">
              Ask your data
              <br />
              <span className="bg-gradient-to-r from-white via-[#cbd5e1] to-[#7dd3fc] bg-clip-text text-transparent">
                anything.
              </span>
            </h1>

            <p className="mt-7 max-w-xl text-[15px] leading-7 text-[#858b95] sm:text-base">
              Turn natural-language questions into SQL queries, useful
              insights and visualizations. Explore your data without
              having to write SQL yourself.
            </p>

            <div className="mt-9 flex flex-col gap-3 sm:flex-row">
              <button
                onClick={onTryFree}
                className="group flex items-center justify-center gap-2.5 rounded-xl bg-white px-4 py-3.5 text-sm font-semibold text-[#101114] shadow-[0_8px_30px_rgba(255,255,255,0.08)] transition-all duration-200 hover:bg-[#f1f3f5] hover:shadow-[0_12px_40px_rgba(255,255,255,0.12)] cursor-pointer"
              >
                <Zap className="h-4 w-4 text-[#2563eb]" />
                Try Now
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
              </button>
            </div>

            <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3">
              <div className="flex items-center gap-2 text-[10px] text-[#666c75]">
                <ShieldCheck className="h-3.5 w-3.5 text-emerald-400/80" />
                Secure authentication
              </div>

              <div className="flex items-center gap-2 text-[10px] text-[#666c75]">
                <Database className="h-3.5 w-3.5 text-blue-400/80" />
                SQLite & custom data
              </div>

              <div className="flex items-center gap-2 text-[10px] text-[#666c75]">
                <Activity className="h-3.5 w-3.5 text-violet-400/80" />
                Usage telemetry
              </div>
            </div>
          </div>

          <div className="relative">
            <div className="absolute rounded-[30px] bg-blue-500/[0.05] blur-3xl" />

            <div className="relative overflow-hidden rounded-2xl border border-white/[0.1] bg-[#101216]">
              <div className="flex h-12 items-center justify-between border-b border-white/[0.07] px-4">
                <div className="flex items-center gap-1.5">
                  <span className="h-2.5 w-2.5 rounded-full bg-[#383c43]" />
                  <span className="h-2.5 w-2.5 rounded-full bg-[#383c43]" />
                  <span className="h-2.5 w-2.5 rounded-full bg-[#383c43]" />
                </div>

                <div className="flex items-center gap-2 rounded-md border border-white/[0.06] bg-white/[0.025] px-3 py-1.5">
                  <Database className="h-3 w-3 text-[#707680]" />
                  <span className="text-[9px] text-[#777d87]">
                    ecommerce.db
                  </span>
                </div>

                <div className="h-5 w-14" />
              </div>

              <div className="grid lg:grid-cols-[0.85fr_1.5fr]">
                <div className="border-b border-white/[0.07] p-5 lg:border-b-0 lg:border-r">
                  <div className="mb-3 flex items-center justify-between">
                    <div>
                      <p className="text-[10px] font-semibold text-[#c9ccd1]">
                        Ask your data
                      </p>

                      <p className="text-[8px] text-[#626771]">
                        Natural language
                      </p>
                    </div>

                    <Sparkles className="h-3.5 w-3.5 text-blue-400" />
                  </div>

                  <div className="rounded-xl border border-white/[0.07] bg-[#0b0d11] p-4">
                    <p className="text-[10px] leading-5 text-[#9da2aa]">
                      What is the total revenue generated by each product
                      category?
                    </p>
                  </div>
                </div>

                <div className="p-5">
                  <div className="mb-4 flex items-center justify-between">
                    <div>
                      <p className="text-[10px] font-semibold text-[#c9ccd1]">
                        Query result
                      </p>

                      <p className="text-[8px] text-[#626771]">
                        Generated, executed, and analyzed automatically
                      </p>
                    </div>

                    <span className="rounded-md bg-emerald-400/[0.07] px-2 py-1 text-[8px] font-medium text-emerald-400">
                      Completed
                    </span>
                  </div>

                  <div className="mb-2 rounded-xl border border-white/[0.06] bg-[#0b0d11] p-3">
                    <div className="mb-2 flex items-center justify-between">
                      <span className="text-[8px] font-medium text-[#777d87]">
                        Generated query
                      </span>

                      <span className="text-[7px] text-[#4f555e]">
                        SQL
                      </span>
                    </div>

                    <div className="overflow-hidden rounded-lg border border-white/[0.04] bg-[#080a0d] px-3 pb-2">
                      <code className="text-[7.5px] leading-4 text-[#8d96a5]">
                        <span className="text-blue-400">SELECT</span>{" "}
                        category,{" "}
                        <span className="text-blue-400">SUM</span>(revenue){" "}
                        <span className="text-blue-400">AS</span> total_revenue{" "}
                        <span className="text-blue-400">FROM</span> orders{" "}
                        <span className="text-blue-400">GROUP BY</span> category
                      </code>
                    </div>
                  </div>

                  <div className="mb-2 grid grid-cols-4 gap-2">
                    {[
                      ["Tokens", "12.4K"],
                      ["Latency", "1.24s"],
                      ["Est. cost", "$0.014"],
                      ["Retries", 1]
                    ].map(([label, value]) => (
                      <div
                        key={label}
                        className="rounded-lg border border-white/[0.06] bg-[#0b0d11] px-2.5 py-2.5"
                      >
                        <p className="text-[7px] text-[#626771]">
                          {label}
                        </p>

                        <p className="mt-1 text-[10px] font-semibold text-[#c9ccd1]">
                          {value}
                        </p>
                      </div>
                    ))}
                  </div>

                  <div className="relative rounded-xl border border-white/[0.06] bg-[#0b0d11] px-5 pb-3 pt-5">
                    <div className="mb-2 flex items-center justify-between">
                      <span className="text-[7px] text-[#626771]">
                        Revenue by category
                      </span>

                      <span className="text-[7px] text-[#4f555e]">
                        USD
                      </span>
                    </div>

                    <div className="relative h-24">
                      <div className="absolute inset-x-0 top-3 border-t border-white/[0.035]" />
                      <div className="absolute inset-x-0 top-1/2 border-t border-white/[0.035]" />
                      <div className="absolute inset-x-0 bottom-0 border-t border-white/[0.035]" />

                      <div className="absolute inset-0 flex items-end justify-around gap-4 px-4">
                        {[
                          ["$42.8k", "68%", "Electronics", "bg-blue-500/70"],
                          ["$34.4k", "55%", "Clothing", "bg-blue-500/55"],
                          ["$26.1k", "42%", "Home", "bg-blue-500/45"],
                          ["$19.7k", "31%", "Sports", "bg-blue-500/35"],
                        ].map(([value, height, name, color]) => (
                          <div
                            key={name}
                            className="flex h-full flex-1 flex-col items-center justify-end"
                          >
                            <span className="mb-1 text-[7px] text-[#777d87]">
                              {value}
                            </span>

                            <div
                              className={`w-full max-w-8 rounded-t ${color}`}
                              style={{ height }}
                            />

                            <span className="mt-2 text-[7px] text-[#555b65]">
                              {name}
                            </span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  <div className="mt-2 grid grid-cols-4 gap-2">
                    {[
                      ["Electronics", "$42.8k"],
                      ["Clothing", "$34.4k"],
                      ["Home", "$26.1k"],
                      ["Sports", "$19.7k"],
                    ].map(([name, value]) => (
                      <div
                        key={name}
                        className="rounded-lg border border-white/[0.06] bg-[#0b0d11] p-2.5"
                      >
                        <p className="truncate text-[7px] text-[#626771]">
                          {name}
                        </p>

                        <p className="mt-1 text-[10px] font-semibold text-[#c9ccd1]">
                          {value}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}